export default async function handler(req, res) {
  // Set CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  try {
    const { url } = req.body;

    if (!url) {
      res.status(400).json({
        success: false,
        error: 'URL is required',
        llms_txt: ''
      });
      return;
    }

    // For now, let's create a simple response to test the API structure
    // We'll implement the full crawling logic in a separate step
    const testResponse = {
      success: true,
      llms_txt: `# Test Website

This is a test response from the API.

Website: ${url}
Generated on: ${new Date().toISOString()}
Total pages crawled: 1

## Navigation
- [Home](${url}): Test Website

## Page Summaries
### Test Website
URL: ${url}
Summary: This is a test website for API verification.

---
This llms.txt file was automatically generated by LLMs.txt Generator.
It provides a structured overview of the website content for AI training and SEO purposes.`,
      pages_crawled: 1
    };

    res.status(200).json(testResponse);

  } catch (error) {
    console.error('API Error:', error);
    res.status(500).json({
      success: false,
      error: `Server error: ${error.message}`,
      llms_txt: ''
    });
  }
} 